---
title: "spider plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(here)
library(tidyverse)
library(patchwork)
library(fmsb)
library(dplyr)
```

```{r}

indicators<- read_csv("condata.csv")

indicators %>% arrange(mentions)

# Color vector
colors_border=c( rgb(0.2,0.5,0.5,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9) )
colors_in=c( rgb(0.2,0.5,0.5,0.4), rgb(0.8,0.2,0.5,0.4) , rgb(0.7,0.5,0.1,0.4) )


bio<-indicators %>% 
  filter(type == "Biological")
  
spider_data1<-bio %>% 
  group_by(group, method) %>% 
  summarise(total_m = sum(mentions, na.rm = T)) %>% 
  pivot_wider(., names_from = "group", values_from = "total_m") %>% 
  column_to_rownames(., var = "method") 

spider_data1[is.na(spider_data1)]<-0

spider_data1<-rbind(rep(145,5), rep(0, 5),spider_data1)
  

radarchart(spider_data1, axistype = 1, seg = 6, pcol = colors_border, pfcol = colors_in, plwd=1.5 , plty=1,
    #custom the grid - order is grid colour, line type, axis labes start, max, increments, net width, group label size 
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0, 150, 25), calcex = 0.8,  cglwd=0.9,
    #custom labels
    vlcex=0.9)

```



```{r}

phys<-indicators %>% 
  filter(type == "Physical")
  


spider_data2<-phys %>% 
  group_by(group, method) %>% 
  summarise(total_m = sum(mentions, na.rm = T)) %>% 
  pivot_wider(., names_from = "group", values_from = "total_m") %>% 
  column_to_rownames(., var = "method") 

spider_data2[is.na(spider_data2)]<-0

spider_data2<-rbind(rep(55,7), rep(0, 7),spider_data2)

radarchart(spider_data2, axistype = 1, seg=6, pcol = colors_border, pfcol = colors_in, plwd=1.5 , plty=1,
    #custom the grid - order is grid colour, line type, axis labes start, max, increments, net width, group label size 
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,60,10), calcex = 0.8, cglwd=0.5,  vlcex=0.01)
    #custom labels i made them 1 to edit in illustrator )

```


```{r}

socio<-indicators %>% 
  filter(type == "Socio-Economic")


spider_data3<-socio %>% 
  group_by(group, method) %>% 
  summarise(total_m = sum(mentions, na.rm = T)) %>% 
  pivot_wider(., names_from = "group", values_from = "total_m") %>% 
  column_to_rownames(., var = "method")

spider_data3[is.na(spider_data3)]<-0

spider_data3<-rbind(rep(20,7), rep(0, 7),spider_data3)

radarchart(spider_data3, axistype = 1, seg = 5, pcol = colors_border, pfcol = colors_in, plwd=1.5 , plty=1,
    #custom the grid - order is grid colour, line type, axis labes start, max, increments, net width, group label size 
    cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,20,4), calcex = 0.8, cglwd=0.9,
    #custom labels
    vlcex=0.9) 

```

lollypop charts to compliment: 



```{r}
# Create data: note in High school for Jonathan:
set.seed(1)
data <-as.data.frame(matrix( sample( 2:20 , 20 , replace=T) , ncol=10))
colnames(data) <- c("math" , "english" , "biology" , "music" , "R-coding", "data-viz" , "french" , "physic", "statistic", "sport" )
data <-rbind(rep(20,10) , rep(0,10) , data)

data

# Barplot
data %>% slice(c(3,4)) %>% t() %>% as.data.frame() %>% add_rownames() %>% arrange(V1) %>% mutate(rowname=factor(rowname, rowname)) #%>%
  ggplot( aes(x=rowname, y=V1)) +
    geom_segment( aes(x=rowname ,xend=rowname, y=V2, yend=V1), color="grey") +
    geom_point(size=5, color="#69b3a2") +
    geom_point(aes(y=V2), size=5, color="#69b3a2", alpha=0.1) +
    coord_flip() +
    theme_ipsum() +
    theme(
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      axis.text = element_text( size=48 )
    ) +
    ylim(0,20) +
    ylab("mark") +
    xlab("")
```

```{r}


social<-scatterindi %>% 
  filter(type == "Socio-Economic") %>% 
ggplot( aes(x=indicator, y=Monitoring)) +
    geom_segment( aes(x=indicator, xend=indicator, y=Monitoring, yend=MSP), color="grey") +
    geom_point(size=5, color="pink", alpha =0.5) +
    geom_point(aes(y=MSP), size=5, color="blue", alpha=0.1) +
    coord_flip() +
    #theme_ipsum() 
    theme(
      panel.grid.minor.y = element_blank(),
      panel.grid.major.y = element_blank(),
      axis.text = element_text( size=8)
    ) +
    ylim(0,10) +
    ylab("") +
    xlab("")

social
```

